title: The Awesome Blog
markdown: kramdown
url: "https://void-ayush.github.io/"
baseurl: "/new_blog"

# for atom feed
author:
  name: VOiD | Ayush Panwar
  email: mailto:ayushpanwar.qu@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
  line_format: '%i'
  gutter_class: 'rouge-gutter'
  code_class: 'rouge-code'
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      


collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
