title: The Awesome Blog
markdown: kramdown
url: "https://void-ayush.github.io/"
baseurl: "/new_blog"

# for atom feed
author:
  name: VOiD | Ayush Panwar
  email: mailto:ayushpanwar.qu@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

      


collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
